### ISSUE TITLE
Quick View Facet to a Table is not working 

### ISSUE THREAD

**Issue by VishnuPriyakadiyala** [SAP-samples/abap-platform-fiori-feature-showcase#10]
Could you please check the Quick View Facet in the sample example? (/DMO/FSA_I_Navigation). Looks like it is not working. Please find the below screenshot

![image](https://github.com/SAP-samples/abap-platform-fiori-feature-showcase/assets/53003348/37f84f99-649f-40a4-b514-b8085afafb42)

**Comment by jessie-cheah** [comment]
Hi Vishnu,
the new release is just out. And QuickView is now working as it should
[https://blogs.sap.com/2023/09/20/the-sap-fiori-elements-feature-showcase-with-rap-whats-new-in-release-2308/](https://blogs.sap.com/2023/09/20/the-sap-fiori-elements-feature-showcase-with-rap-whats-new-in-release-2308/)
Regards,
Jessie
