### ISSUE TITLE
Pull the new features ( 2302 release ) of Side effects into SAP BTP Trail system

### ISSUE THREAD

**Issue by koradaramjee789** [SAP-samples/abap-platform-fiori-feature-showcase#12]
Hi ,

Can you please pull the new features ( 2302 release - side effects )  into SAP BTP Trail system. 
Unfortunately , we cannot do from our end as they are in /DMO/ namespace. 

system url : https://405e183a-28de-4d81-92fd-4d082cf16a3f.abap.us10.hana.ondemand.com

Best wishes,
Ramjee Korada

**Comment by koradaramjee789** [comment]
I created another trail account and it also does not have 2302 features.

https://c75f608d-4148-434a-88e1-64b75d24911a.abap.us10.hana.ondemand.com_/

**Comment by jessie-cheah** [comment]
Hi Ramjee,
apologies for the delay. As we will release 2308 soon, we will not be pulling 2302 into the BTP trial system in the meantime.
I'll update here when release 2308 is also pulled into the trial system.
Regards,
Jessie

**Comment by jessie-cheah** [comment]
Hi Ramjee,

release 2308 is available now in https://c75f608d-4148-434a-88e1-64b75d24911a.abap.us10.hana.ondemand.com/

Regards,
Jessie
